#!/bin/bash

echo "🚀 Загрузка файлов AR ARENA на сервер..."
echo ""
echo "Файлы для загрузки:"
echo "  • auth.js - система авторизации"
echo "  • index.html - главная страница"
echo "  • debug.html - страница отладки"
echo ""
echo "Выполните команду вручную:"
echo ""
echo "scp ~/Desktop/AR\ ARENA/auth.js ~/Desktop/AR\ ARENA/index.html ~/Desktop/AR\ ARENA/debug.html root@83.166.246.186:/var/www/neurocamp/arena/"
echo ""
echo "После загрузки:"
echo "1. Откройте приложение в Telegram"
echo "2. Нажмите красную кнопку DEBUG"
echo "3. Сделайте скриншот раздела 'User Data'"